"""Build protocol examples from the locally captured experiment evidence."""
import sys,json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'src'))
from trace_hunter.adapters import normalize,span,ref
from trace_hunter.protocol import validate
from trace_hunter.identity import upgrade_header
from trace_hunter.analysis import analyze
for file,fmt,out in [('claude-orange-5.execution-trace.json','claude-export','claude-orange.trace.json'),('doubao-2.1-pro.trajectory.json','doubao-export','doubao-pro.trace.json'),('orange-5.0.trajectory.json','doubao-export','doubao-orange.trace.json'),('doubao-2.1-pro.sqlite.trajectory.json','doubao-export','doubao-pro-web.trace.json'),('orange-5.0.sqlite.trajectory.json','doubao-export','doubao-orange-web.trace.json')]:
    t=validate(normalize(ROOT/'apps/trace-lab'/file,fmt));(ROOT/'examples'/out).write_text(json.dumps(t,ensure_ascii=False)+'\n');a=analyze(t);print(out,a['tool_count'],a['model_request_count'],a['tokens']['output_tokens'])
minimal={'schema_version':'trace-hunter/1.0','run':{'id':'example-ledger','title':'协议最小示例 · 读配置并写台账','task_key':'example-ledger','query':'读取配置，创建一条测试台账','harness':'Example harness','model':'Example model','status':'completed','time_basis':'同一进程单调时钟，相对任务起点的毫秒数'},'collector':{'name':'example','version':'1.0'},'sources':[{'id':'original','name':'synthetic-fixture','sha256':hashlib.sha256(b'synthetic-fixture').hexdigest()}],'coverage':{'tools':'complete','model_requests':'complete'},'phases':[{'id':'task','name':'执行','purpose':'task','start_ms':0,'end_ms':12000}],'spans':[span('m1','Model',kind='model',request_id='req-1',start_ms=0,end_ms=6000,status='ok',usage={'input_tokens':1200,'output_tokens':400,'cache_read_tokens':1000,'cache_write_tokens':0,'thinking_tokens':100}),span('read','Read',start_ms=6000,end_ms=7000,status='ok',input={'path':'config.json'},output={'currency':'CNY'}),span('m2','Model',kind='model',request_id='req-2',start_ms=7000,end_ms=10000,status='ok',usage={'input_tokens':1400,'output_tokens':200,'cache_read_tokens':1200,'cache_write_tokens':0,'thinking_tokens':50}),span('write','Write',start_ms=10000,end_ms=12000,status='ok',input={'amount':100},output={'record_id':'demo-1'})],'links':[{'from':'m1','to':'read','type':'invokes'},{'from':'m2','to':'write','type':'invokes'}],'evidence':[{'id':'check-1','kind':'assertion','name':'写入金额与输入一致','status':'passed','detail':'示例断言：回读金额 100。此例为合成数据。','span_ids':['write'],'source':ref('/assertions/0')}]}
minimal=upgrade_header(minimal);minimal['run']['id']='example-ledger-v1.1';validate(minimal);(ROOT/'examples/minimal.trace.json').write_text(json.dumps(minimal,ensure_ascii=False,indent=2)+'\n')
